### ISSUE TITLE
Combine mask + a given maskfile into a standalone binary

### ISSUE THREAD

**Issue by jakedeichert** [jakedeichert/mask#1]
It should be able to take a maskfile and turn it into a standalone rust binary... not sure how possible this even is. The maskfile would need to be embedded into the mask binary or something.

This would create an easy way to make general cli programs that can be distributed to a team.

**Comment by brandonkal** [comment]
Hmmm. You could always support a shebang in the markdown file.
That would mean an extra heading at the top when rendered.

Instead of building a standalone binary, I would suggest implementing something like the `deno install` command.

For instance you could do something like:
```
mask --install https://example.com/your-mask-cli.md
```

Mask would handle:
1. Downloading the markdown file to `~/.mask/https/example.com/your-mask-cli.md`
2. Creating a simple wrapping shell script
3. Place that shell script in the path

**Comment by jakedeichert** [comment]
Very interesting idea! I'll have to think about this...

My goal with this issue was to allow a scenario like this:

- team member wants to build a cli for their team to use
- they write the cli with mask and a maskfile because it's easy
- they want to deploy a single binary (no maskfile) to their entire dev team (this was me a few years ago but i wrote a node cli)


But requiring team members to install mask would slightly defeat the purpose of this.

However, i'm kind of thinking about just closing this issue. Anyone could just distribute a global maskfile to their team easily enough and tell them to install mask via github releases or eventually homebrew... so this idea I had isn't as valuable as I once thought.

**Comment by feep** [comment]
> Hmmm. You could always support a shebang in the markdown file.

I like this.

Not sure how I would work with the extra `<h1>`. But it is inert, just a render issue. 

I’d use it.

- Would require a mask binary.
- Would not require an alias or a wrapper script.

**Comment by jakedeichert** [comment]
Closing in favour of a GitHub discussion thread instead: https://github.com/jakedeichert/mask/discussions/76
