### ISSUE TITLE
--list flag

### ISSUE THREAD

**Issue by brandonkal** [jakedeichert/mask#48]
It would be useful if `mask --list` printing a list of available commands.

**Comment by jakedeichert** [comment]
`mask --help` does this... unless you mean you want an output that shows ALL commands in the tree?

**Comment by brandonkal** [comment]
Oops. That works well.

**Comment by brandonkal** [comment]
@jakedeichert I've got things installed now and see that `mask --help` generates a traditional help screen.

The idea with `--list` is to return a newline separated list of available subcommands for things like bash completion and feeding into [fzf](https://github.com/junegunn/fzf).

As an example use case, mask could be well suited to produce an output selection similar to the [pet exec](https://github.com/knqyf263/pet) experience.

**Comment by jakedeichert** [comment]
Regarding bash/zsh/fish completion, there was some discussion in #18. I'm waiting for clap v3 to release and will reconsider if shell completion generation should be built into mask.

Exposing a `--list` arg I'm unsure about. Just dumping all cmds as rows to stdout is not really following any standard format and though it may work for some tools, it won't be powerful enough for others. Especially if argument options aren't dumped with the cmds...

Instead of mask dumping an unorganized list everything... it should be easy for people to parse the maskfile for cmd headings with a simple bash(_insert lang here_) script. It just needs to find lines with headings `#` and count the depth... very simple.

**Comment by brandonkal** [comment]
Yes. It is a bit annoying that clap sorts subcommands rather than allowing it to be the order in the markdown file.

**Comment by jakedeichert** [comment]
> Instead of mask dumping an unorganized list of everything... it should be easy for people to parse the maskfile for cmd headings with a simple bash(insert lang here) script. It just needs to find lines with headings # and count the depth... very simple.

Closing in favour of this recommendation I gave instead of building this into mask.
