### ISSUE TITLE
Improve homebrew formula and automate publishing process

### ISSUE THREAD

**Issue by jakedeichert** [jakedeichert/mask#72]
I just noticed that the [homebrew formula](https://github.com/Homebrew/homebrew-core/pull/56193/files) depends on rust to compile. 

A better and faster way is to just download the precompiled `mask-vX.X.X-x86_64-apple-darwin.zip` which is [built](https://github.com/jakedeichert/mask/blob/master/.github/workflows/release.yml) and [attached](https://github.com/jakedeichert/mask/releases) to every release. This way the homebrew user doesn't need to have the rust toolchain installed.

**Comment by jakedeichert** [comment]
There's a related [PR](https://github.com/jakedeichert/mask/pull/64) for automating the homebrew formula process, so we should do this before that merges.

**Comment by vladimyr** [comment]
> I just noticed that the [homebrew formula](https://github.com/Homebrew/homebrew-core/pull/56193/files) depends on rust to compile.

Only if you decided to build it locally. ☝️ There are prebuilt binaries named bottles: https://formulae.brew.sh/api/formula/mask.json

> A better and faster way is to just download the precompiled `mask-vX.X.X-x86_64-apple-darwin.zip` which is [built](https://github.com/jakedeichert/mask/blob/master/.github/workflows/release.yml?rgh-link-date=2020-08-11T01%3A45%3A26Z) and [attached](https://github.com/jakedeichert/mask/releases) to every release. This way the homebrew user doesn't need to have the rust toolchain installed.

Due to the formula being _bottled_ there is no need to alter it (users don't need to download rust and compile it locally). Also, Homebrew doesn't let people distribute binaries they built around → https://docs.brew.sh/Acceptable-Formulae#we-dont-like-binary-formulae

**Comment by jakedeichert** [comment]
@vladimyr thanks for clarifying! Didn't know about bottling 😅
